import type { Metadata } from 'next'
import './globals.css'
import { UiProviders } from '@/providers/ui-providers'
import { ColorModeScript } from '@chakra-ui/react'
import theme from '@/theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <UiProviders>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          {children}
        </UiProviders>
      </body>
    </html>
  )
}
